apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      containers:
        - name: estoque
          image: devops-estoque:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
